Import("env","env_etc")
env = env.Clone()
env.Prepend(LIBS=["lunus"])
if (env_etc.enable_cuda):
  env.Prepend(LIBS=["lunus_cuda"])

#env.Prepend(LIBPATH=["/opt/local/lib/libomp","/opt/cudatoolkit/10.0/lib64"])

env.SharedLibrary(
  target="#lib/lunus_ext",
  source="lunus_ext.cpp"
)
