Import("env")
env = env.Clone()
env.Prepend(LIBS=["lunus","gomp","cudart"])
env.Prepend(LIBPATH=["/opt/local/lib/libomp","/opt/cudatoolkit/10.0/lib64"])

env.SharedLibrary(
  target="#lib/lunus_ext",
  source="lunus_ext.cpp"
)
