#!/bin/csh -f
#
# MAKEMAKE - Make the master Makefile for a c-code package
# Author: Mike Wall
# Date: 11/21/95
# Description:  
#               When in the ./c/src directory, this creates a makefile which
#            builds the executables.
# Usage:
#               makemake <makefile>
#
# Save the old one:
#
cp $1 $1.sav
#
# Get the header:
#
cat $1.head > $1
#
# Executable list:
#
echo "all: \" >> $1
ls -1 *.c | awk '{print "\t"substr($0,0,length()-2)" \\"}' >> ${C_HOME}/src/$1
echo "libmw.a" | awk '{print "\t"$0}'>> ${C_HOME}/src/$1
#
# Build executables:
#
echo "#" >> ${C_HOME}/src/$1
echo "# Executables:" >> ${C_HOME}/src/$1
echo "#" >> ${C_HOME}/src/$1
ls -1 *.c | awk '{print substr($0,0,length()-2)":"$1" ${DEPENDS}\n\t${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}"}' >> ${C_HOME}/src/$1
#
# Build library functions:
#
echo "#" >> ${C_HOME}/src/$1
echo "# Library functions:" >> ${C_HOME}/src/$1
echo "#" >> ${C_HOME}/src/$1
cd ${C_HOME}/lib
ls -1 *.c | awk '{print substr($0,0,length()-2)".o:"$1" lunus.h"}' >> ${C_HOME}/src/$1
echo '.c.o:' >> ${C_HOME}/src/$1
echo '$(CC) -c -o ${L}/$*.o $(CFLAGS) ${L}/$*.c' | awk '{print "\t"$0}' >> ${C_HOME}/src/$1
#
# Build libraries:
#
echo "#" >> ${C_HOME}/src/$1
echo "# Libraries:" >> ${C_HOME}/src/$1
echo "#" >> ${C_HOME}/src/$1
/bin/echo -n "libmw.a: " >> ${C_HOME}/src/$1
ls -1 *.c | awk '{printf "\\\n\t"substr($0,0,length()-2)".o "}' >> ${C_HOME}/src/$1
echo "" >> ${C_HOME}/src/$1
echo 'cd ${L}; rm libmw.a; $(AR) $(ARFLAGS) libmw.a *.o' | awk '{print "\t"$0}' >> ${C_HOME}/src/$1



