VPATH=${C_HOME}/src:${C_HOME}/lib:${C_HOME}/bin:${C_HOME}/include
CC=cc
CFLAGS= -g3 -L${C_HOME}/lib -O2 -I${C_HOME}/include
AR=ar
ARFLAGS=cr
SHELL=/bin/csh
LIBS=-lmw -lm -lmalloc 
DEPENDS=mwmask.h libmw.a
S=${C_HOME}/src
B=${C_HOME}/bin
L=${C_HOME}/lib
all: \
	  filter \
	  histim \
	  genmap \
	  genlat \
	  maskimg \
	  ovldim \
	  xpl2mw \
	  rf2char \
	  mapbound \
	  map2lat \
	  minr \
	  binasc \
	  culllt \
	  solidlt \
	  shimlt \
	  shim4lt \
	  histlt \
	  scalelt \
	  dfsqrlt \
	  dfrflt \
	  subrflt \
	  mulsclt \
	  constlt \
	  explt \
	  mullt \
	  divlt \
	  sumlt \
	  sublt \
	  xflt \
	  symlt \
	  fftlt \
	  gausslt \
	  avgrlt \
	  avsqrlt \
	  hdrlt \
	  rf2lt \
	  taglt \
	  avgr \
	  fftim \
	  ftfltim \
	  avgrim \
	  avgim \
	  avgsqim \
          buttim \
	  avgrf \
	  subrfim \
	  minrim \
	  scaleim \
	  mulrfim \
	  mulrf \
	  smthim \
	  modeim \
	  medim \
	  xfmask \
	  ratioim \
	  constim \
	  waveim \
	  noiseim \
	  peakim \
	  tagim \
	  subim \
	  sumim \
	  avsqrim \
	  divrf \
	  sumrf \
	  constrf \
	  windim \
	  cutim \
	  polarim \
	  normim \
          mulim \
	  subrf \
	  nign \
	  punchim \
	  thrshim \
	  rmpkim \
	  intdfim \
	  df2im \
	  libmw.a 
#
#Executables:
#
fftim:fftim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
ftfltim:ftfltim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
df2im:df2im.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
histim:histim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
intdfim:intdfim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
rmpkim:rmpkim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
thrshim:thrshim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
punchim:punchim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
nign:nign.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
subrf:subrf.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
mulim:mulim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
polarim:polarim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
normim:normim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
windim:windim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
cutim:cutim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
sumrf:sumrf.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
constrf:constrf.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
divrf:divrf.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
avsqrim:avsqrim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
subim:subim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
sumim:sumim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
tagim:tagim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
constim:constim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
waveim:waveim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
noiseim:noiseim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
peakim:peakim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
ratioim:ratioim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
xfmask:xfmask.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
smthim:smthim.c ${DEPENDS} 
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
modeim:modeim.c ${DEPENDS} 
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
medim:medim.c ${DEPENDS} 
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
scaleim:scaleim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
minrim:minrim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
avgr:avgr.c ${DEPENDS}   
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
avgrim:avgrim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
avgim:avgim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
avgsqim:avgsqim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
buttim:buttim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
avgrf:avgrf.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
culllt:culllt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
shimlt:shimlt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
shim4lt:shim4lt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
solidlt:solidlt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
histlt:histlt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
scalelt:scalelt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
dfsqrlt:dfsqrlt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
dfrflt:dfrflt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
subrflt:subrflt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
mulsclt:mulsclt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
constlt:constlt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
explt:explt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
mullt:mullt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
divlt:divlt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
sumlt:sumlt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
sublt:sublt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
symlt:symlt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
xflt:xflt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
fftlt:fftlt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
gausslt:gausslt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
avgrlt:avgrlt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
avsqrlt:avsqrlt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
hdrlt:hdrlt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
rf2lt:rf2lt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
taglt:taglt.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
subrfim:subrfim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
mulrfim:mulrfim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
mulrf:mulrf.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
binasc:binasc.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
minr:minr.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
map2lat:map2lat.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
mapbound:mapbound.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
rf2char:rf2char.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
xplmw:xpl2mw.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
genmap:genmap.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
genlat:genlat.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
maskimg:maskimg.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
ovldim:ovldim.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
wfilter:filter.c ${DEPENDS}
	${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}
#
#Library functions:
#
ldf2im.o:ldf2im.c mwmask.h
lintdfim.o:lintdfim.c mwmask.h
lreaddf.o:lreaddf.c mwmask.h
lwritedf.o:lwritedf.c mwmask.h
lrmpkim.o:lrmpkim.c mwmask.h
lthrshim.o:lthrshim.c mwmask.h
lpunchim.o:lpunchim.c mwmask.h
lnign.o:lnign.c mwmask.h
lsubrf.o:lsubrf.c mwmask.h
lmulim.o:lmulim.c mwmask.h
lpolarim.o:lpolarim.c mwmask.h
lnormim.o:lnormim.c mwmask.h
lwindim.o:lwindim.c mwmask.h
lcutim.o:lcutim.c mwmask.h
lsumrf.o:lsumrf.c mwmask.h
lconstrf.o:lconstrf.c mwmask.h
ldivrf.o:ldivrf.c mwmask.h
lreadrf.o:lreadrf.c mwmask.h
lwriterf.o:lwriterf.c mwmask.h
lsubim.o:lsubim.c mwmask.h
lsumim.o:lsumim.c mwmask.h
ltagim.o:ltagim.c mwmask.h
lconstim.o:lconstim.c mwmask.h
lwaveim.o:lwaveim.c mwmask.h
lnoiseim.o:lnoiseim.c mwmask.h
lpeakim.o:lpeakim.c mwmask.h
lratioim.o:lratioim.c mwmask.h
lmin.o:lmin.c mwmask.h
ltordata.o:ltordata.c mwmask.h
lxavgr.o:lxavgr.c mwmask.h
lxfmask.o:lxfmask.c mwmask.h
lsmthim.o:lsmthim.c mwmask.h
lmodeim.o:lmodeim.c mwmask.h
lmedim.o:lmedim.c mwmask.h
lxavgrim.o:lxavgrim.c mwmask.h
lavsqrim.o:lavsqrim.c mwmask.h
lbuttim.o:lbuttim.c mwmask.h
lscaleim.o:lscaleim.c mwmask.h
lavgrim.o:lavgrim.c mwmask.h
lavgim.o:lavgim.c mwmask.h
lavgsqim.o:lavgsqim.c mwmask.h
lavgrf.o:lavgrf.c mwmask.h
lculllt.o:lculllt.c mwmask.h
lshimlt.o:lshimlt.c mwmask.h
lshim4lt.o:lshim4lt.c mwmask.h
lsolidlt.o:lsolidlt.c mwmask.h
lscalelt.o:lscalelt.c mwmask.h
ldfsqrlt.o:ldfsqrlt.c mwmask.h
ldfrflt.o:ldfrflt.c mwmask.h
lsubrflt.o:lsubrflt.c mwmask.h
lmulsclt.o:lmulsclt.c mwmask.h
lconstlt.o:lconstlt.c mwmask.h
lexplt.o:lexplt.c mwmask.h
lmullt.o:lmullt.c mwmask.h
ldivlt.o:ldivlt.c mwmask.h
lsumlt.o:lsumlt.c mwmask.h
lsublt.o:lsublt.c mwmask.h
lsymlt.o:lsymlt.c mwmask.h
lxflt.o:lxflt.c mwmask.h
lfft.o:lfft.c mwmask.h
lgausslt.o:lgausslt.c mwmask.h
lavgrlt.o:lavgrlt.c mwmask.h
lavsqrlt.o:lavsqrlt.c mwmask.h
lrf2lt.o:lrf2lt.c mwmask.h
ltaglt.o:ltaglt.c mwmask.h
lminr.o:lminr.c mwmask.h
lchbyte.o:lchbyte.c mwmask.h
lupdbd.o:lupdbd.c mwmask.h
lgetpks.o:lgetpks.c mwmask.h
lgetovld.o:lgetovld.c mwmask.h
lgetmat.o:lgetmat.c mwmask.h
lpunch.o:lpunch.c mwmask.h
lgetanls.o:lgetanls.c mwmask.h
lgensv.o:lgensv.c mwmask.h
lavgr.o:lavgr.c mwmask.h
lreadim.o:lreadim.c mwmask.h
lwriteim.o:lwriteim.c mwmask.h
lreadlt.o:lreadlt.c mwmask.h
lwritelt.o:lwritelt.c mwmask.h
lwritesh.o:lwritesh.c mwmask.h
linitim.o:linitim.c mwmask.h
linitlt.o:linitlt.c mwmask.h
lfreeim.o:lfreeim.c mwmask.h
lfreelt.o:lfreelt.c mwmask.h
lsubrfim.o:lsubrfim.c mwmask.h
lmulrfim.o:lmulrfim.c mwmask.h
lmulrf.o:lmulrf.c mwmask.h
lminrim.o:lminrim.c mwmask.h
.c.o:
		$(CC) -c -o ${L}/$*.o $(CFLAGS) ${L}/$*.c
#
#Libraries:
#
libmw.a: \
          lavgr.o \
	  lwritesh.o \
	  lculllt.o \
	  lshimlt.o \
	  lshim4lt.o \
	  lsolidlt.o \
	  lscalelt.o \
	  ldfsqrlt.o \
	  ldfrflt.o \
	  lsubrflt.o \
	  lmulsclt.o \
	  lconstlt.o \
	  lexplt.o \
	  lmullt.o \
	  ldivlt.o \
	  lsumlt.o \
	  lsublt.o \
	  lsymlt.o \
	  lxflt.o \
	  lfft.o \
	  lgausslt.o \
	  lavgrlt.o \
	  lavsqrlt.o \
	  lrf2lt.o \
	  ltaglt.o \
	  lminr.o \
	  lchbyte.o \
	  lupdbd.o \
	  lgetpks.o \
	  lgetovld.o \
	  lgetmat.o \
	  lpunch.o \
	  lgetanls.o \
	  lgensv.o \
	  lavgrim.o \
	  lavgim.o \
	  lavgsqim.o \
          lbuttim.o \
	  lavgrf.o \
	  lreadim.o \
	  lsubrfim.o \
	  lwriteim.o \
	  lreadlt.o \
	  lwritelt.o \
	  lminrim.o \
	  lxavgrim.o \
	  lavsqrim.o \
	  lscaleim.o \
	  lfreeim.o \
	  lfreelt.o \
	  lmulrfim.o \
	  lmulrf.o \
	  linitim.o \
	  linitlt.o \
	  lxfmask.o \
	  lsmthim.o \
	  lmodeim.o \
	  lmedim.o \
	  lxavgr.o \
	  ltordata.o \
	  lratioim.o \
	  lconstim.o \
	  lwaveim.o \
	  lnoiseim.o \
	  lpeakim.o \
	  ltagim.o \
	  lsubim.o \
	  lsumim.o \
	  ldivrf.o \
	  lwriterf.o \
	  lreadrf.o \
	  lconstrf.o \
	  lsumrf.o \
	  lmin.o \
	  lpolarim.o \
	  lnormim.o \
          lmulim.o \
	  lsubrf.o \
	  lnign.o \
	  lpunchim.o \
	  lthrshim.o \
	  lrmpkim.o \
	  lintdfim.o \
	  lreaddf.o \
	  lwritedf.o \
	  ldf2im.o \
	  lwindim.o \
	  lcutim.o
	cd ${L}; $(AR) $(ARFLAGS) $@ $?








