#!/bin/csh -f
#
# MAKEMAKE - Make the master Makefile for a c-code package
# Author: Mike Wall
# Date: 11/21/95
# Description:  
#               When in the ./c/src directory, this creates a makefile which
#            builds the executables.
# Usage:
#               makemake <makefile>
#
# Save the old one:
#
cp $1 $1.sav
#
# Get the header:
#
cat $1.head > $1
#
# Executable list:
#
echo "all: \" >> $1
ls -1 *.c | gawk '{print "\t"substr($0,0,length()-2)" \\"}' >> ${C_HOME}/src/$1
echo "\tlibmw.a" >> ${C_HOME}/src/$1
#
# Build executables:
#
echo "#\n# Executables:\n#" >> ${C_HOME}/src/$1
ls -1 *.c | gawk '{print substr($0,0,length()-2)":"$1" ${DEPENDS}\n\t${CC} ${CFLAGS} -o ${B}/$@ ${S}/$@.c ${LIBS}"}' >> ${C_HOME}/src/$1
#
# Build library functions:
#
echo "#\n# Library functions:\n#" >> ${C_HOME}/src/$1
cd ${C_HOME}/lib
ls -1 *.c | gawk '{print substr($0,0,length()-2)".o:"$1" mwmask.h"}' >> ${C_HOME}/src/$1
echo '.c.o:\n\t$(CC) -c -o ${L}/$*.o $(CFLAGS) ${L}/$*.c' >> ${C_HOME}/src/$1
#
# Build libraries:
#
echo "#\n# Libraries:\n#\nlibmw.a: \" >> ${C_HOME}/src/$1
ls -1 *.c | gawk '{print "\t"substr($0,0,length()-2)".o \\"}' >> ${C_HOME}/src/$1
echo '\t;cd ${L}; $(AR) $(ARFLAGS) $@ $?' >> ${C_HOME}/src/$1



